language: generic
sudo: required
services :
  - docker
before_install:
  - docker build -t docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true docker-react npm run test

deploy:
  edge: true
  provider: elasticbeanstock
  region: "us-east-1"
  app: " Docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-263423822079"
  bucket_path: "Docker-react"
  on:
      branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
